HID: asus: Add depends on USB_HID to HID_ASUS Kconfig option
Since commit 4bc43a421218 ("HID: asus: Add
hid_is_using_ll_driver(usb_hid_driver) check") the hid-asus.c depends
on the usb_hid_driver symbol. Add a depends on USB_HID to Kconfig to
fix missing symbols errors in hid-asus when USB_HID is not enabled.

Fixes: 4bc43a421218 ("HID: asus: Add hid_is_using_ll_driver(usb_hid_driver) check")
Reported-by: kbuild test robot <lkp@intel.com>
Signed-off-by: Hans de Goede <hdegoede@redhat.com>
Signed-off-by: Jiri Kosina <jkosina@suse.cz>
(cherry picked from commit c4f0126d487f3c68ab19ccb7c561e8fbf3ea2247)
BugLink: https://bugs.launchpad.net/bugs/1957007
[krzysztof: backport is needed to fix Azure build error:
 ERROR: "usb_hid_driver" [drivers/hid/hid-asus.ko] undefined!
 because hid-asus uses hid_is_usb()]
Signed-off-by: Krzysztof Kozlowski <krzysztof.kozlowski@canonical.com>